#!/usr/bin/env bash
# Install haproxy and config 2 server
apt-get update
apt-get -y install haproxy=1.6.\*
echo "ENABLED=1" >> /etc/default/haproxy
sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 63404-web-01 100.27.13.45 check\n\tserver 63404-web-02:80 54.237.32.9:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
